spring.datasource.url=jdbc:postgresql://db.render.com:5432/jyothi_swaroop_reddy
spring.datasource.username=jyothi_swaroop_reddy_user
spring.datasource.password=61GLCbjlQ6OoxnDhz8rvBCdARTzp4JDt
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect